<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_lab extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_lab_model');
    } 

    /*
     * Listing of tb_lab
     */
    function index()
    {
        $data['tb_lab'] = $this->Tb_lab_model->get_all_tb_lab();
        
        $data['_view'] = 'tb_lab/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_lab
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nama_lab' => $this->input->post('nama_lab'),
				'keterangan' => $this->input->post('keterangan'),
            );
            
            $tb_lab_id = $this->Tb_lab_model->add_tb_lab($params);
            redirect('tb_lab/index');
        }
        else
        {            
            $data['_view'] = 'tb_lab/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_lab
     */
    function edit($id_lab)
    {   
        // check if the tb_lab exists before trying to edit it
        $data['tb_lab'] = $this->Tb_lab_model->get_tb_lab($id_lab);
        
        if(isset($data['tb_lab']['id_lab']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nama_lab' => $this->input->post('nama_lab'),
					'keterangan' => $this->input->post('keterangan'),
                );

                $this->Tb_lab_model->update_tb_lab($id_lab,$params);            
                redirect('tb_lab/index');
            }
            else
            {
                $data['_view'] = 'tb_lab/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_lab you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_lab
     */
    function remove($id_lab)
    {
        $tb_lab = $this->Tb_lab_model->get_tb_lab($id_lab);

        // check if the tb_lab exists before trying to delete it
        if(isset($tb_lab['id_lab']))
        {
            $this->Tb_lab_model->delete_tb_lab($id_lab);
            redirect('tb_lab/index');
        }
        else
            show_error('The tb_lab you are trying to delete does not exist.');
    }
    
}
