<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_pasien extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_pasien_model');
    } 

    /*
     * Listing of tb_pasien
     */
    function index()
    {
        $data['tb_pasien'] = $this->Tb_pasien_model->get_all_tb_pasien();
        
        $data['_view'] = 'tb_pasien/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_pasien
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nomer_pasien' => $this->input->post('nomer_pasien'),
				'nama_pasien' => $this->input->post('nama_pasien'),
				'alamat' => $this->input->post('alamat'),
				'no_hp' => $this->input->post('no_hp'),
				'no_hp_wali' => $this->input->post('no_hp_wali'),
            );
            
            $tb_pasien_id = $this->Tb_pasien_model->add_tb_pasien($params);
            redirect('tb_pasien/index');
        }
        else
        {            
            $data['_view'] = 'tb_pasien/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_pasien
     */
    function edit($id_pasien)
    {   
        // check if the tb_pasien exists before trying to edit it
        $data['tb_pasien'] = $this->Tb_pasien_model->get_tb_pasien($id_pasien);
        
        if(isset($data['tb_pasien']['id_pasien']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nomer_pasien' => $this->input->post('nomer_pasien'),
					'nama_pasien' => $this->input->post('nama_pasien'),
					'alamat' => $this->input->post('alamat'),
					'no_hp' => $this->input->post('no_hp'),
					'no_hp_wali' => $this->input->post('no_hp_wali'),
                );

                $this->Tb_pasien_model->update_tb_pasien($id_pasien,$params);            
                redirect('tb_pasien/index');
            }
            else
            {
                $data['_view'] = 'tb_pasien/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_pasien you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_pasien
     */
    function remove($id_pasien)
    {
        $tb_pasien = $this->Tb_pasien_model->get_tb_pasien($id_pasien);

        // check if the tb_pasien exists before trying to delete it
        if(isset($tb_pasien['id_pasien']))
        {
            $this->Tb_pasien_model->delete_tb_pasien($id_pasien);
            redirect('tb_pasien/index');
        }
        else
            show_error('The tb_pasien you are trying to delete does not exist.');
    }
    
}
