<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_sampel extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_sampel_model');
    } 

    /*
     * Listing of tb_sampel
     */
    function index()
    {
        $data['tb_sampel'] = $this->Tb_sampel_model->get_all_tb_sampel();
        
        $data['_view'] = 'tb_sampel/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_sampel
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'status_sampel' => $this->input->post('status_sampel'),
				'nomer_pasien' => $this->input->post('nomer_pasien'),
				'kategori_sampel' => $this->input->post('kategori_sampel'),
				'tgl_ambil_sampel' => $this->input->post('tgl_ambil_sampel'),
				'keterangan' => $this->input->post('keterangan'),
            );
            
            $tb_sampel_id = $this->Tb_sampel_model->add_tb_sampel($params);
            redirect('tb_sampel/index');
        }
        else
        {            
            $data['_view'] = 'tb_sampel/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_sampel
     */
    function edit($id_sampel)
    {   
        // check if the tb_sampel exists before trying to edit it
        $data['tb_sampel'] = $this->Tb_sampel_model->get_tb_sampel($id_sampel);
        
        if(isset($data['tb_sampel']['id_sampel']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'status_sampel' => $this->input->post('status_sampel'),
					'nomer_pasien' => $this->input->post('nomer_pasien'),
					'kategori_sampel' => $this->input->post('kategori_sampel'),
					'tgl_ambil_sampel' => $this->input->post('tgl_ambil_sampel'),
					'keterangan' => $this->input->post('keterangan'),
                );

                $this->Tb_sampel_model->update_tb_sampel($id_sampel,$params);            
                redirect('tb_sampel/index');
            }
            else
            {
                $data['_view'] = 'tb_sampel/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_sampel you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_sampel
     */
    function remove($id_sampel)
    {
        $tb_sampel = $this->Tb_sampel_model->get_tb_sampel($id_sampel);

        // check if the tb_sampel exists before trying to delete it
        if(isset($tb_sampel['id_sampel']))
        {
            $this->Tb_sampel_model->delete_tb_sampel($id_sampel);
            redirect('tb_sampel/index');
        }
        else
            show_error('The tb_sampel you are trying to delete does not exist.');
    }
    
}
