<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_track extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_track_model');
    } 

    /*
     * Listing of tb_track
     */
    function index()
    {
        $data['tb_track'] = $this->Tb_track_model->get_all_tb_track();
        
        $data['_view'] = 'tb_track/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_track
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'status_pemeriksaan' => $this->input->post('status_pemeriksaan'),
				'id_sampel' => $this->input->post('id_sampel'),
				'id_lab' => $this->input->post('id_lab'),
				'id_pasien' => $this->input->post('id_pasien'),
				'time_proses' => $this->input->post('time_proses'),
				'keterangan_hasil' => $this->input->post('keterangan_hasil'),
            );
            
            $tb_track_id = $this->Tb_track_model->add_tb_track($params);
            redirect('tb_track/index');
        }
        else
        {            
            $data['_view'] = 'tb_track/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_track
     */
    function edit($id)
    {   
        // check if the tb_track exists before trying to edit it
        $data['tb_track'] = $this->Tb_track_model->get_tb_track($id);
        
        if(isset($data['tb_track']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'status_pemeriksaan' => $this->input->post('status_pemeriksaan'),
					'id_sampel' => $this->input->post('id_sampel'),
					'id_lab' => $this->input->post('id_lab'),
					'id_pasien' => $this->input->post('id_pasien'),
					'time_proses' => $this->input->post('time_proses'),
					'keterangan_hasil' => $this->input->post('keterangan_hasil'),
                );

                $this->Tb_track_model->update_tb_track($id,$params);            
                redirect('tb_track/index');
            }
            else
            {
                $data['_view'] = 'tb_track/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_track you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_track
     */
    function remove($id)
    {
        $tb_track = $this->Tb_track_model->get_tb_track($id);

        // check if the tb_track exists before trying to delete it
        if(isset($tb_track['id']))
        {
            $this->Tb_track_model->delete_tb_track($id);
            redirect('tb_track/index');
        }
        else
            show_error('The tb_track you are trying to delete does not exist.');
    }
    
}
