<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_sampel_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_sampel by id_sampel
     */
    function get_tb_sampel($id_sampel)
    {
        return $this->db->get_where('tb_sampel',array('id_sampel'=>$id_sampel))->row_array();
    }
        
    /*
     * Get all tb_sampel
     */
    function get_all_tb_sampel()
    {
        $this->db->order_by('id_sampel', 'desc');
        return $this->db->get('tb_sampel')->result_array();
    }
        
    /*
     * function to add new tb_sampel
     */
    function add_tb_sampel($params)
    {
        $this->db->insert('tb_sampel',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_sampel
     */
    function update_tb_sampel($id_sampel,$params)
    {
        $this->db->where('id_sampel',$id_sampel);
        return $this->db->update('tb_sampel',$params);
    }
    
    /*
     * function to delete tb_sampel
     */
    function delete_tb_sampel($id_sampel)
    {
        return $this->db->delete('tb_sampel',array('id_sampel'=>$id_sampel));
    }
}
