<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_track_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_track by id
     */
    function get_tb_track($id)
    {
        return $this->db->get_where('tb_track',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all tb_track
     */
    function get_all_tb_track()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('tb_track')->result_array();
    }
        
    /*
     * function to add new tb_track
     */
    function add_tb_track($params)
    {
        $this->db->insert('tb_track',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_track
     */
    function update_tb_track($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tb_track',$params);
    }
    
    /*
     * function to delete tb_track
     */
    function delete_tb_track($id)
    {
        return $this->db->delete('tb_track',array('id'=>$id));
    }
}
